#define YAP_ROOTDIR       "/tmp/eye/windows"
#define YAP_BINDIR	    "/tmp/eye/windows/bin"
#define YAP_LIBDIR	    "/tmp/eye/windows/lib/Yap"
#define YAP_SHAREDIR	    "/tmp/eye/windows/share"
#define YAP_PL_SRCDIR	    "/tmp/eye/windows/share/Yap/pl"
#define YAP_STARTUP   "startup.yss"
#define YAP_VERSION 60203
#define MYDDAS_VERSION	    "MYDDAS-0.9.1"
#define YAP_ARCH	    "i686-mingw32"
#define YAP_LIBS	    "-lgmp -lpsapi -lwsock32  -lz"
#define YAP_YAPLIB	    "yap.dll"
#define YAP_CC	    "gcc"
#define YAP_CFLAGS	    "-O3 -Wall -Wstrict-prototypes -Wmissing-prototypes  -DCUT_C=1  -DCOROUTINING=1 -DRATIONAL_TREES=1 -DDEPTH_LIMIT=1 -DHAVE_CONFIG_H -D_YAP_NOT_INSTALLED_=1 -I. -I../H -I../OPTYap -I../BEAM -I../MYDDAS"
#define YAP_LDFLAGS    "-Wl,--large-address-aware "
#define YAP_SHLIB_SUFFIX    "." "dll"
#define YAP_TIMESTAMP "1328697231"
#define YAP_SVERSION   "YAP 6.2.3 (i686-mingw32): Wed Feb  8 11:33:51 RST 2012"
