#define YAP_ROOTDIR       "/tmp/eye/linux"
#define YAP_BINDIR	    "/tmp/eye/linux/bin"
#define YAP_LIBDIR	    "/tmp/eye/linux/lib/Yap"
#define YAP_SHAREDIR	    "/tmp/eye/linux/share"
#define YAP_PL_SRCDIR	    "/tmp/eye/linux/share/Yap/pl"
#define YAP_STARTUP   "startup.yss"
#define YAP_VERSION 60203
#define MYDDAS_VERSION	    "MYDDAS-0.9.1"
#define YAP_ARCH	    "i686-linux"
#define YAP_LIBS	    "-lgmp -lresolv -lnss_dns -lnss_files -lcrypt -lstdc++ -lm  -lreadline -lncurses -lz -ldl -lnsl"
#define YAP_YAPLIB	    "libYap.a"
#define YAP_CC	    "gcc"
#define YAP_CFLAGS	    "-DBP_FREE -O3 -fomit-frame-pointer -Wall -Wstrict-prototypes -Wmissing-prototypes  -DCUT_C=1  -DCOROUTINING=1 -DRATIONAL_TREES=1 -DDEPTH_LIMIT=1 -DHAVE_CONFIG_H -D_YAP_NOT_INSTALLED_=1 -I. -I../H -I../OPTYap -I../BEAM -I../MYDDAS"
#define YAP_LDFLAGS    "-rdynamic  -L/home/jdroo/yap-6/arch -Wl,-R/tmp/eye/linux/lib -Wl,-R,/tmp/eye/linux/lib/Yap"
#define YAP_SHLIB_SUFFIX    "." "so"
#define YAP_TIMESTAMP "1328696090"
#define YAP_SVERSION   "YAP 6.2.3 (i686-linux): Wed Feb  8 11:14:50 CET 2012"
